### ISSUE TITLE
What tech/stack should we use?

### ISSUE THREAD

**Issue by enitiz** [2lbProgramming/SPACEGAME#3]
> EDIT!
> The [LÖVE engine](https://love2d.org/) seems to be leading the pack out of all the options.
> 
> So far the options are:
> - The [Godot Engine](https://godotengine.org/)
> - The [LÖVE engine](https://love2d.org/)
> - Bareback, with [SDL2](https://www.libsdl.org/index.php)

**Comment by Textmode** [comment]
So far the discussion seems to be leaning towards the [Godot Engine](https://godotengine.org/), though I have to admit I'm having a bit of trouble getting it to work. (though thats not unusually, most things fail to run on the stack of compressed cardboard I use as a computer)

Since this is a 2d game, I suppose its worth pointing out the existance of [LÖVE](https://love2d.org/) which is portable uses the lua language which only I use. I mention it only because.

Alternately, we could leave all reason behind and use [SDL2](https://www.libsdl.org/index.php) (optionally in combination with OpenGL).

**Comment by enitiz** [comment]
@Textmode How tough is it to learn lua and get started with developing using LÖVE as compared to Godot Engine route?

**Comment by llllvvuu** [comment]
I've heard only good things about LOVE.

Lua is pretty easy to learn, it's kind of like python. I use it only for Lua/Torch and it's not an issue at all

**Comment by Textmode** [comment]
To learn lua? Not hard, its a small language, with a small core library, and in the usual imperative style. no assurances that you like it ofc.
As for LÖVE, well its deliberately aimed at newbies, so its generally fairly easy to use.

**Comment by enitiz** [comment]
Sounds good enough to me. I am okay with learning up lua for this. 

SDL2? I am not sure.

**Comment by Textmode** [comment]
So far we seem to be going for LÖVE.

**Comment by tttmmmiii** [comment]
Lua/LÖVE

**Comment by Textmode** [comment]
What about visuals? Love supports shreenshaders, does Godot support something similar?

**Comment by llllvvuu** [comment]
Why don't we use bare OpenGL and write all our shaders in GLSL, that'd be really fun, right??????

**Comment by enitiz** [comment]
Heard from someone in #programming to never use are OpenGL. What is the 
good/bad thing about using it vs going with something live LOVE?

**Comment by llllvvuu** [comment]
It was me who said to never use OpenGL :p
it's just way too much coding for way too little return

**Comment by enitiz** [comment]
I see. I'd still go towards Lua/LOVE where everyone is heading. 

@Textmode Not sure but they have an article about [screen reading shaders](http://docs.godotengine.org/en/latest/tutorials/2d/screen-reading_shaders.html).

**Comment by tttmmmiii** [comment]
Lua/LOVE sounds fine to me too. Let's just go with that.

**Comment by tttmmmiii** [comment]
I've only ever used github for my own personal stuff so I hope closing the issue was the right thing to do haha.
